name: GitHub Actions Vercel Preview Deployment
on:
  pull_request:
    types:
      - opened
jobs:
  Tests:
    name: Tests # название конктретной работы в pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  # клонируем репозиторый
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn # устанавливаем зависимости

      - name: Test
        run: yarn test # запускаем скрипт тестами
